### ISSUE TITLE
Have types exports on generated file?

### ISSUE THREAD

**Issue by SrBrahma** [fabien0102/ts-to-zod#81]
## Feature description

The generated file only contains the schemas. I would have no problemas for my small files to have the `export type MyType = z.infer<typeof myTypeSchema>`. Looks like I have to add them manually to the generated file.

### Input

```ts
export type MyType = z.number();
```

### Output

```ts
export const myTypeSchema = z.number();
export type MyType = z.infer<typeof myTypeSchema>;
```

**Comment by fabien0102** [comment]
Hello!

Just for challenge a bit the feature request, what is your usecase? Normally you should already have the original types around (since this is the source for ts-to-zod) and those types will always be better since they have the documentation for example.

![image](https://user-images.githubusercontent.com/1761469/170947137-d544cf3c-fb46-4f0f-99c7-bc1736208eb3.png)

You will loose this usefull piece of information if you retrieve the type with `z.infer`

**Comment by SrBrahma** [comment]
Hi!

Typescript is smart!

![image](https://user-images.githubusercontent.com/28177550/171045287-517cab80-e2a0-4527-9b42-6438dbebc7f1.png)

Even using infer, it keeps the JSDoc comments from the schema!

**Comment by SrBrahma** [comment]
Also, I wouldn't trust having a separated schema from the type.

If I change the type but forget to change the schema, there would be bugs.

**Comment by fabien0102** [comment]
Good to know that typescript can follow! Quite amazing indeed!

Regarding the trust issue, my solution is usually to check this on CI, as example in this repository:
![image](https://user-images.githubusercontent.com/1761469/171138507-9cfe7102-b302-4130-af3f-53ebbdbed2a3.png)

So if something is not in sync, typescript will throw (you can also check if the git diff is empty)

Is this could solve your issue?

**Comment by Ionshard** [comment]
I came across this tool while looking for something to help us migrate towards Zod with some of our types. We don't really want to keep them in sync, we're looking to move toward Zod as the single source of truth. I understand that this was not the original usecase but this would be really helpful for people who want to do one-time migrations.
